services:
  app:
    build:
      args:
        user: edo
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: bvf
    container_name: bvf_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - bvf

  nginx:
    image: nginx:1.17-alpine
    container_name: bvf-nginx
    restart: unless-stopped
    ports:
      - "81:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - bvf

  db:
    image: mysql:5.7
    container_name: bvf_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Cravates123
      MYSQL_DATABASE: bvf
      MYSQL_USER: admin
      MYSQL_PASSWORD: Cravates123
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "9001:3306"
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - bvf

networks:
  bvf:
    driver: bridge